### ISSUE TITLE
Add support for the Spectator and Competitors

### ISSUE THREAD

**Issue by teknologika** [derrickmoeller/PostItNoteRacing#1]
Hi Derrick,

It would be great if you could add support in your plugin to read from the competitors data structure and support the Car being spectated as an alternate to the Driver. This would allow your plugin to provide relatives and data when watching replays or in spectator mode, broadcasting or as Race Control.

The competitors structure is under > SessionData._DriverInfo._Drivers and has information on every player that joins the session. As far as I am aware the Spectator never becomes an "opponent" as they are not actually driving.

So the main trick is to get the currently obxerved CarIdx  as opposed to the "Driver" and then use that as the point to build relatives and standings from the opponents structure.

I have done all of this in my own plugin, but 95% of it could go in the bin if your plugin supported this and worked in spactating mode.

Some other data is also available if you are running in admin mode such as incidents for every car, but 95% of the telemetery isn't.

Thanks in  advance,

Bruce

**Comment by derrickmoeller** [comment]
I've created a branch, but I don't spectate races and I'm not sure how to access the observed car. You're welcome to look at what I've done, if you get the IsSpectator property working I can likely get the gaps working.

**Comment by teknologika** [comment]
It's not the IsSpectator it is the CameraCar for example

 _statusDatabase = e.Data.NewData;
 DataSampleEx irData = e.Data.NewData.GetRawDataObject() as DataSampleEx;
 SessionData._DriverInfo._Drivers[] competitors = irData.SessionData.DriverInfo.CompetingDrivers;

 long cameraCarIdx = irData.Telemetry.CamCarIdx;
 string cameraCarName = irData.SessionData.DriverInfo.CompetingDrivers[cameraCarIdx].UserName;
 
 then you match the camera car name. I think then what should work is writing it back into the _statusDatabase.
 
 Hoever in the code I wrote it keeps getting over written in the update loop so it "flashes"

Here is how I think it shold work, but I am missing something 

 if (e.Data.GameRunning && e.Data.NewData != null)
{
    Game = new Game(e.Data.GameName);
    if (Game.IsSupported != false)
    {
        _statusDatabase = e.Data.NewData;

        // update the data every frame
        DataSampleEx irData = e.Data.NewData.GetRawDataObject() as DataSampleEx;
        SessionData._DriverInfo._Drivers[] competitors = irData.SessionData.DriverInfo.CompetingDrivers;

        long cameraCarIdx = irData.Telemetry.CamCarIdx;
        string cameraCarName = irData.SessionData.DriverInfo.CompetingDrivers[cameraCarIdx].UserName;

        foreach (var opponent in _statusDatabase.Opponents) {
            if (string.Equals(cameraCarName, opponent.Name)) {
                // If we are the camera car, make us the player as well
                opponent.IsPlayer = true;
            }

            // We need to loop because there is no CarIdx in opponents
            foreach (var competitor in competitors) {
                float[] bestLapTimes = (float[])irData.Telemetry.FirstOrDefault(x => x.Key == "CarIdxBestLapTime").Value;
                float[] lastLapTimes = (float[])irData.Telemetry.FirstOrDefault(x => x.Key == "CarIdxLastLapTime").Value;

                var newBestLapTime = bestLapTimes[competitor.CarIdx];
                if (newBestLapTime > 0) {
                    opponent.BestLapTime = TimeSpan.FromSeconds(newBestLapTime);
                }

                var newLastLapTime = lastLapTimes[competitor.CarIdx];
                if (newLastLapTime > 0) {
                    opponent.LastLapTime = TimeSpan.FromSeconds(newLastLapTime);
                }
            }
        }



        if (e.Is60Hz)
        {

**Comment by teknologika** [comment]
I'll DM you on Discord.

**Comment by teknologika** [comment]
The other thing is that the getplayerleaderboardposition() position javascriipt needs to return the camera car, not the actual spectating car, as they don't actually have a position. That way when you change to observe another car, gaps timing and 
everyting should switch to be from that car's perspective.

**Comment by derrickmoeller** [comment]
I'm just not invested in solving this, any solution I create would also be iRacing specific which is not what I desire for this plugin. I think somebody else with more interest in this use case will need to tackle this.

**Comment by teknologika** [comment]
No worries .. I completely understand .. I'll build it myself. :-)
